{
 "title": "SensorData",
 "time": { "from": "now-90s", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Pressure Sensor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "pressure" }
     ]
    }
   ]
  },
  {
   "title": "Events per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "eventsPerSecond",
     "query": "SELECT \"value\" FROM \"eventsPerSecond\" WHERE (\"key\" = 'pressure') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "pressure" }
     ]
    }
   ]
  },
  {
   "title": "Events Processed per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"eventsProcessedPerSecond\" WHERE (\"key\" = 'pressure') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}